pipeline:
  build:
    image: node:latest
    commands:
      - npm install
      - npm run build

  publish:
    image: plugins/docker
    repo: roikiermedia/europeinabottle
    secrets:
      username: dockeruser
      password: dockerpassword
    when:
      branch: master
