pipeline:
  build:
    image: node:latest
    commands:
      - npm install
      - npm run build

  publish:
    image: plugins/docker
    registry: hub.docker.com
    repo: roikiermedia/europeinabottle
    secrets:
      - username: dockeruser
      - password: dockerpassword
    when:
      branch: master
